# Generated by Django 3.0.4 on 2020-03-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserHeadImg', models.ImageField(blank=True, upload_to='ImageCollect/UserHeadImg')),
                ('UserName', models.CharField(max_length=50)),
                ('PassWord', models.CharField(max_length=50)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
