# Generated by Django 3.0.4 on 2020-03-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Jurisdiction',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
