# Generated by Django 3.0.4 on 2020-04-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20200330_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Jurisdiction',
            field=models.CharField(blank=True, default='00', max_length=400),
        ),
    ]
