# Generated by Django 3.0.4 on 2020-04-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_users_issuperuseer'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
