# Generated by Django 3.0.4 on 2020-04-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20200405_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='UserHeadImg',
            field=models.CharField(max_length=400),
        ),
    ]
