# Generated by Django 3.0.3 on 2020-03-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParamsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailName', models.CharField(max_length=100)),
                ('paramsCreateTime', models.DateTimeField()),
                ('paramsUpdateTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ParamsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paramsName', models.CharField(max_length=100)),
                ('paramsCode', models.CharField(max_length=50)),
                ('paramsCreateTime', models.DateTimeField()),
                ('paramsUpdateTime', models.DateTimeField()),
            ],
        ),
    ]
