# Generated by Django 3.0.3 on 2020-03-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramssettings',
            name='paramsCreateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paramssettings',
            name='paramsUpdateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
