# Generated by Django 3.0.3 on 2020-03-15 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0002_auto_20200315_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramscontent',
            name='detailCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paramscontent',
            name='detailParentParam',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='blogAdmin.ParamsSettings'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paramscontent',
            name='paramsCreateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paramscontent',
            name='paramsUpdateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
