# Generated by Django 3.0.4 on 2020-03-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0004_paramscontent_detailparentparamid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paramscontent',
            name='detailParentParamCode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
