# Generated by Django 3.0.4 on 2020-03-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0005_paramscontent_detailparentparamcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paramscontent',
            old_name='paramsCreateTime',
            new_name='CreateTime',
        ),
        migrations.RenameField(
            model_name='paramscontent',
            old_name='paramsUpdateTime',
            new_name='UpdateTime',
        ),
        migrations.RenameField(
            model_name='paramssettings',
            old_name='paramsCreateTime',
            new_name='CreateTime',
        ),
        migrations.RenameField(
            model_name='paramssettings',
            old_name='paramsUpdateTime',
            new_name='UpdateTime',
        ),
    ]
