# Generated by Django 3.0.4 on 2020-03-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0006_auto_20200316_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paramscontent',
            name='detailParentParam',
            field=models.CharField(max_length=100),
        ),
    ]
