# Generated by Django 3.0.4 on 2020-03-30 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0007_auto_20200316_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paramscontent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='paramssettings',
            name='id',
        ),
        migrations.AddField(
            model_name='paramscontent',
            name='detail_params_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='paramssettings',
            name='params_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
