# Generated by Django 3.0.4 on 2020-04-04 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0008_auto_20200330_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexTab',
            fields=[
                ('IndexTabID', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('IndexTabName', models.CharField(max_length=20)),
                ('IsShowTab', models.BooleanField(default=True)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='paramscontent',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paramssettings',
            name='IsDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
