# Generated by Django 3.0.4 on 2020-04-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0009_auto_20200405_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='indextab',
            name='IndexTabContent',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indextab',
            name='IsShowTab',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
