# Generated by Django 3.0.4 on 2020-04-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0010_auto_20200405_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='indextab',
            name='IndexTabCode',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
