# Generated by Django 3.0.4 on 2020-04-05 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogAdmin', '0011_indextab_indextabcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexTab',
        ),
    ]
