# Generated by Django 3.0.3 on 2020-03-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogIndex', '0002_auto_20200317_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentAuthor', models.CharField(max_length=50)),
                ('commentHeadImg', models.CharField(blank=True, max_length=200)),
                ('commentContent', models.CharField(blank=True, max_length=400)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
