# Generated by Django 3.0.3 on 2020-03-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogIndex', '0004_commentdetail_parentarticleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdetail',
            name='parentArticleTitle',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
