# Generated by Django 3.0.4 on 2020-03-30 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogIndex', '0005_commentdetail_parentarticletitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articledetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='commentdetail',
            name='id',
        ),
        migrations.AddField(
            model_name='articledetail',
            name='article_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='commentdetail',
            name='comment_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
