# Generated by Django 3.0.4 on 2020-04-05 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogIndex', '0007_auto_20200405_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexTab',
            fields=[
                ('IndexTabID', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('IndexTabName', models.CharField(max_length=20)),
                ('IndexTabContent', models.TextField()),
                ('IndexTabCode', models.CharField(max_length=20)),
                ('IsShowTab', models.BooleanField(blank=True, default=True)),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
