# Generated by Django 3.0.4 on 2020-04-05 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogIndex', '0008_indextab'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexImage',
            fields=[
                ('IndexImageID', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('IndexImage', models.ImageField(upload_to='images/IndexImage')),
                ('CreateTime', models.DateTimeField(auto_now_add=True)),
                ('ConnectArticleID', models.CharField(max_length=100)),
                ('ConnectArticleName', models.CharField(max_length=100)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='HomePageCarouselImage',
        ),
    ]
