# Generated by Django 3.0.4 on 2020-04-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogIndex', '0010_auto_20200406_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='indeximage',
            name='ImageName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
