# Generated by Django 3.0.4 on 2020-04-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogIndex', '0011_indeximage_imagename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indeximage',
            name='ImageName',
        ),
    ]
