# Generated by Django 3.0.4 on 2020-04-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogIndex', '0012_remove_indeximage_imagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='indeximagemanagement',
            name='ShowOnIndex',
            field=models.BooleanField(default=False),
        ),
    ]
