# Generated by Django 3.0.4 on 2020-04-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogIndex', '0014_auto_20200408_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetail',
            name='articleViews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
